name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'notest')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.13"
          - "3.13t"
        # NOTE: Example for excluding OS/python version.
        #   - os: windows-latest
        #     python-version: 3.6
        #   - os: macos-latest
        #     python-version: 3.8
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.20"
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uv run pytest -s
